# Generated by Django 5.0.6 on 2024-07-04 05:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
