# Generated by Django 5.0.6 on 2024-07-04 05:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
